apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
#  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30088
